// Mocks generated by Mockito 5.4.6 from annotations
// in smartmeter/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:smartmeter/models/app_model.dart' as _i4;
import 'package:smartmeter/services/energy_repo.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [EnergyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnergyRepository extends _i1.Mock implements _i2.EnergyRepository {
  MockEnergyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.Users?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i3.Stream<_i4.Users?>.empty(),
          )
          as _i3.Stream<_i4.Users?>);

  @override
  _i3.Future<void> signIn(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [email, password]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> register(
    String? email,
    String? password,
    Map<String, dynamic>? userData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, password, userData]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.Appliance>> getAppliancesStream(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getAppliancesStream, [userId]),
            returnValue: _i3.Stream<List<_i4.Appliance>>.empty(),
          )
          as _i3.Stream<List<_i4.Appliance>>);

  @override
  _i3.Stream<List<_i4.Appliance>> getPendingVerificationStream() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingVerificationStream, []),
            returnValue: _i3.Stream<List<_i4.Appliance>>.empty(),
          )
          as _i3.Stream<List<_i4.Appliance>>);

  @override
  _i3.Future<void> addAppliance(String? userId, _i4.Appliance? app) =>
      (super.noSuchMethod(
            Invocation.method(#addAppliance, [userId, app]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateApplianceStatus(
    String? userId,
    String? appId,
    String? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateApplianceStatus, [userId, appId, status]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> triggerDisaggregation(
    String? userId,
    String? billId,
    double? totalBill,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#triggerDisaggregation, [
              userId,
              billId,
              totalBill,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
